using Microsoft.CodeAnalysis.CSharp.Syntax;
using QB.UI;
using System;
using System.Collections.Generic;
using System.Drawing;
using static QB.Collections;
//using System.Drawing;

namespace QB
{

    public static class Modules
    {

        public static Module Get(string id)
        {
            lock (Root.ModuleDict)
            {
                if (Root.ModuleDict.ContainsKey(id))
                    return Root.ModuleDict[id];
                else
                    return null;
            }
        }
    }

    public class ModuleSettings
    {
        public float Ks { get; set; }
        public float Tu { get; set; }
        public float Tg { get; set; }
    }

    


    public class Module : Signal
    {

        public uint State;
        public string Status;
        public uint Mode;
        public uint Alert;
        public string StreamRead = "";
        public string StreamWrite = null;
     

        public ModuleSettings ModuleSettings { get; set; }

        //    public string CreatedBy = null; //may hold information who originally created the module (can, user, code, etc.)

        public bool StateUpdate = false;


        /// <summary>
        /// REad (autogenerated Signal)
        /// </summary>
        //public Signal Read = new Signal("Read", 0, "", "red");
        /// <summary>
        /// Set (autogenerated Signal)
        /// </summary>
        ///
        
        public Signal Set = new Signal("Set", value: 0, unit: "", colorName: "green");
        public Signal PreSet = new Signal("PreSet", value: double.NaN, unit: "", colorName: "violet");
        /// <summary>
        /// Out (autogenerated Signal)
        /// </summary>
        public Signal Out = new Signal("Out", value: double.NaN, unit: "", colorName: "blue");
        /// <summary>
        /// OutUnit
        /// </summary>
        public string OutUnit = "";
        //   public List<string> LogList = new List<string>();

        public bool OnAir = false;
        public int NetId = 0;
        public int Command = -1;
        //  public int lastCommand = -1;
        public DateTime LastUpdate;




        /*
        public string Tag(string name)
        {
            if (Tags.ContainsKey(name))
            {
                if (Tags[name] is string)
                    return Tags[name] as string;
                if (Tags[name] is double);
                    return "" + Tags[name];
                if (Tags[name] is float)
                    return "" + Tags[name];
            }
            return "#";
        }
        */
        //    public ConcurrentDictionary<string, object> Tags = new ConcurrentDictionary<string, object>();







        /*
        public object Tag(string key, object value)
        {
            if (!Tags.ContainsKey(key))
                Tags.Add(key, null);
            Tags[key] = value;
            return Tags[key];
        }

        public object Tag(string key)
        {
            lock (Tags)
            {
                if (!Tags.ContainsKey(key))
                    Tags.Add(key, null);
                return Tags[key];
            }
        }
        */
        /*
        public Module(string name) : base (name)
        {
        }

        public Module(string name, double value, string unit, string color, string id = null) : base(name, value, unit, color, id)
        {

        }
        */
        public Module(string name, string text = null, double value = double.NaN, string unit = null, string colorName = null, System.Drawing.Color? color = null) : base(name, text: text, value: value, unit: unit, colorName: colorName, color: color)
        {
        
            if (QB.Logger.LibDebugLevel >= 2) QB.Logger.Debug($"::new Module({name})");
            Set.Text = Text + ".Set";
            Set.Unit = Unit;
            Out.Text = Text + ".Out";

        }


        ~Module()
        {
            if (QB.Logger.LibDebugLevel >= 2) QB.Logger.Debug($"::~Module({this.Name})");
        }

        public override void Destroy()
        {
            if (QB.Logger.LibDebugLevel >= 2) QB.Logger.Debug($"::destroy Module({this.Name})");
        }
    }


    public class TimerModule : Module
    {
        protected Timer _timer;
      
        public TimerModule(string name, string text = null) : base(name, text: text)
        {
            if (QB.Logger.LibDebugLevel >= 2) QB.Logger.Debug($"::new TimerModule({name})");
            _timer = new Timer(name, 1 * 1000);
        }


        public virtual void Run()
        {
            _timer.Run();
        }

        public virtual void Destroy()
        {
            _timer.Destroy();
        }

    }

    public class StringSignal : Item
    {
        string _value;

        public string Value 
        { 
        get { return _value; }
            set 
            { 
                _value = value; 
                lastValueUpdate = DateTime.UtcNow; 
            }
        }

        public DateTime lastValueUpdate;

        public StringSignal(string name,string text= null, string value = "") : base(name)
        {
            if (text == null)
                Text = "#" + name;
            else
                Text = text;

            _value = value;

            lastValueUpdate = DateTime.UtcNow;

        }
    }

    public class Signal : Item
    {
        public Signal(string name, string text = null, double value = double.NaN, string unit = "", string colorName = null, System.Drawing.Color? color = null, Access access = default)
            : base(name, null)
        {
            if (QB.Logger.LibDebugLevel >= 2)
                QB.Logger.Debug($"::new Signal({name})");

            Text = text ?? ("#" + name);
            ValueFromNet = value;
            Unit = unit;
            Color = color ?? Color.Black;
            if (colorName != null)
                Color = Misc.ParseColor(colorName);
            Access = access;
        }

        public string Text;
        private Access Access;

        public Queue<double> NetUploadQueue = new Queue<double>();
        public DateTime lastValueUpdate = DateTime.Now;
        private double _value = double.NaN;

        public double Value
        {
            get => _value;
            set
            {
                if ((DateTime.Now - lastValueUpdate).TotalSeconds > 0.9)
                    recorder?.Add(_value);
                lock (this)
                {
                    NetUploadQueue.Enqueue(value);
                    if (NetUploadQueue.Count > 10) NetUploadQueue.Dequeue();
                    _value = value;
                }
                recorder?.Add(value);
            }
        }
        public double ValueFromNet
        {
            set
            {
                if ((DateTime.Now - lastValueUpdate).TotalSeconds > 0.9)
                    recorder?.Add(_value);
                lock (this)
                {
                    _value = value;
                }
                recorder?.Add(value);
            }
        }

        private static int _RecorderCount = 0;
        private QB.Collections.Recorder recorder = null;

        public Collections.Recorder getRecorder()
        {
            if (recorder == null)
                recorder = new Collections.Recorder(Collections.RECORDERSIZE_);
            return recorder;
        }

        public Collections.Recorder initRecorder()
        {
            return initRecorder(Collections.RECORDERSIZE_);
        }

        public Collections.Recorder initRecorder(int size)
        {
            if (recorder == null)
            {
                recorder = new Collections.Recorder(size);
                _RecorderCount++;
            }
            // ❌ KEIN Array.Resize mehr, da kein Array mehr existiert!
            // Stattdessen ggf. Hinweis/Log:
            else
            {
                if (recorder.Capacity != size)
                {
                    QB.Logger.Warn($"Recorder size change not supported after initialization (requested {size}, has {recorder.Capacity})");
                }
            }

            return recorder;
        }

        public fformat Format { get; set; } = new fformat();
        public string DefaultDisplayFormat = "F5";
        public string Unit { get; set; }
        public System.Drawing.Color Color { get; set; } = Color.Black;

        public override string ToString()
        {
            try
            {
                return $"{Value.ToString(DefaultDisplayFormat)}{(string.IsNullOrEmpty(Unit) ? "" : " " + Unit)}";
            }
            catch
            {
                return "!Format";
            }
        }

        public string ValueRule { get; set; } = "";

        ~Signal()
        {
            if (QB.Logger.LibDebugLevel >= 2)
                QB.Logger.Debug($"::~Signal({this.Name})");
        }

        public override void Destroy()
        {
            if (QB.Logger.LibDebugLevel >= 2)
                QB.Logger.Debug($"::destroy Signal({this.Name})");
            recorder = null; // wird vom GC übernommen
        }


    }



}
